CREATE TABLE `proman`.`User` ( `UID` INT(10) NOT NULL AUTO_INCREMENT , `UName` VARCHAR(30) NOT NULL , `Email` VARCHAR(100) NOT NULL , `FName` VARCHAR(30) NOT NULL , `LName` VARCHAR(30) NOT NULL , `AddrStr` VARCHAR(50) NULL DEFAULT NULL , `AddrCity` VARCHAR(30) NULL DEFAULT NULL , `AddrState` VARCHAR(30) NULL DEFAULT NULL , `AddrZip` VARCHAR(5) NULL DEFAULT NULL , `TimeZone` VARCHAR(50) NULL DEFAULT NULL , `Pwd` VARCHAR(100) NULL DEFAULT NULL , `DataHash` VARCHAR(30) NULL DEFAULT NULL , `LastLogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `IsOnline` TINYINT(1) NOT NULL DEFAULT '0' , `AccType` TINYINT(3) NOT NULL DEFAULT '0' , `DateAdded` DATE NULL DEFAULT NULL , `IsRestricted` TINYINT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (`UID`), UNIQUE `Email` (`Email`), UNIQUE `UName` (`UName`)) ENGINE = InnoDB;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON *.* TO 'ProManDb'@'%' IDENTIFIED BY PASSWORD '*0F389CEEE31FB21B3E006B477F98CCF914B24E1F';

GRANT ALL PRIVILEGES ON `proman`.* TO 'ProManDb'@'%';

